"""Create new Prompt and PromptMedia models

Revision ID: 22ca4699f133
Revises: 03a61012d6f9
Create Date: 2023-02-03 21:22:39.068860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "22ca4699f133"
down_revision = "03a61012d6f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompts_new",
        sa.Column("_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "twitter_id",
            sa.String(length=30, collation="utf8mb4_unicode_ci"),
            nullable=False,
        ),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("date_added", sa.DateTime(), nullable=False),
        sa.Column(
            "word", sa.String(length=30, collation="utf8mb4_unicode_ci"), nullable=False
        ),
        sa.Column(
            "content",
            sa.String(length=2048, collation="utf8mb4_unicode_ci"),
            nullable=False,
        ),
        sa.Column("host_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["host_id"], ["hosts._id"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("_id"),
        sa.UniqueConstraint("twitter_id"),
        comment="Store the #vss365 Prompts.",
    )
    op.create_table(
        "prompt_media",
        sa.Column("_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "media",
            sa.String(length=512, collation="utf8mb4_unicode_ci"),
            nullable=True,
        ),
        sa.Column(
            "alt_text",
            sa.String(length=1000, collation="utf8mb4_unicode_ci"),
            nullable=True,
        ),
        sa.Column("prompt_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["prompt_id"], ["prompts_new._id"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("_id"),
        comment="Store the #vss365 Prompt media.",
    )
    op.create_table_comment(
        "prompts",
        "Legacy table for storing prompts.",
        existing_comment=None,
        schema=None,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        "prompts", existing_comment="Legacy table for storing prompts.", schema=None
    )
    op.drop_table("prompt_media")
    op.drop_table("prompts_new")
    # ### end Alembic commands ###
