"""Create indexes

Revision ID: 958aed64a39e
Revises: 22ca4699f133
Create Date: 2023-02-03 22:17:12.872245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "958aed64a39e"
down_revision = "22ca4699f133"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_audit_api_keys_key_id"), "audit_api_keys", ["key_id"], unique=False
    )
    op.create_index(op.f("ix_prompts_uid"), "prompts", ["uid"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prompts_uid"), table_name="prompts")
    op.drop_index(op.f("ix_audit_api_keys_key_id"), table_name="audit_api_keys")
    # ### end Alembic commands ###
