"""Add ApiKey.has_media

Revision ID: b5f3addc3fb1
Revises: 958aed64a39e
Create Date: 2023-02-24 23:34:07.829758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b5f3addc3fb1"
down_revision = "958aed64a39e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("api_keys", sa.Column("has_media", sa.Boolean(), nullable=False))
    op.add_column(
        "audit_api_keys", sa.Column("has_media", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("audit_api_keys", "has_media")
    op.drop_column("api_keys", "has_media")
    # ### end Alembic commands ###
