"""Update ApiKeyHistory column names

Revision ID: cf379e9a2dc4
Revises: 958aed64a39e
Create Date: 2023-02-27 17:46:51.241885

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "cf379e9a2dc4"
down_revision = "958aed64a39e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audit_api_keys",
        "has_host",
        new_column_name="has_hosts",
        existing_nullable=False,
        existing_server_default="0",
        existing_type=sa.types.Boolean,
    )
    op.alter_column(
        "audit_api_keys",
        "has_api_key",
        new_column_name="has_keys",
        existing_nullable=False,
        existing_server_default="0",
        existing_type=sa.types.Boolean,
    )
    op.alter_column(
        "audit_api_keys",
        "has_broadcast",
        new_column_name="has_notifications",
        existing_nullable=False,
        existing_server_default="0",
        existing_type=sa.types.Boolean,
    )
    op.alter_column(
        "audit_api_keys",
        "has_prompt",
        new_column_name="has_prompts",
        existing_nullable=False,
        existing_server_default="0",
        existing_type=sa.types.Boolean,
    )
    op.alter_column(
        "audit_api_keys",
        "has_subscription",
        new_column_name="has_emails",
        existing_nullable=False,
        existing_server_default="0",
        existing_type=sa.types.Boolean,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audit_api_keys",
        "has_hosts",
        new_column_name="has_host",
        existing_nullable=False,
        existing_server_default="0",
        existing_type=sa.types.Boolean,
    )
    op.alter_column(
        "audit_api_keys",
        "has_keys",
        new_column_name="has_api_key",
        existing_nullable=False,
        existing_server_default="0",
        existing_type=sa.types.Boolean,
    )
    op.alter_column(
        "audit_api_keys",
        "has_notifications",
        new_column_name="has_broadcast",
        existing_nullable=False,
        existing_server_default="0",
        existing_type=sa.types.Boolean,
    )
    op.alter_column(
        "audit_api_keys",
        "has_prompts",
        new_column_name="has_prompt",
        existing_nullable=False,
        existing_server_default="0",
        existing_type=sa.types.Boolean,
    )
    op.alter_column(
        "audit_api_keys",
        "has_emails",
        new_column_name="has_subscription",
        existing_nullable=False,
        existing_server_default="0",
        existing_type=sa.types.Boolean,
    )
    # ### end Alembic commands ###
