"""Rename PromptMedia.media

Revision ID: f862f100f6fb
Revises: e03e08dd379c
Create Date: 2023-05-19 21:43:18.260997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "f862f100f6fb"
down_revision = "e03e08dd379c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prompt_media",
        sa.Column(
            "file", sa.String(length=512, collation="utf8mb4_unicode_ci"), nullable=True
        ),
    )
    op.drop_constraint("prompt_media_ibfk_1", "prompt_media", type_="foreignkey")
    op.create_foreign_key(
        None,
        "prompt_media",
        "prompts_new",
        ["prompt_id"],
        ["_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("prompt_media", "media")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prompt_media",
        sa.Column(
            "media",
            mysql.VARCHAR(
                charset="utf8mb4", collation="utf8mb4_unicode_ci", length=512
            ),
            nullable=True,
        ),
    )
    op.drop_constraint(None, "prompt_media", type_="foreignkey")
    op.create_foreign_key(
        "prompt_media_ibfk_1",
        "prompt_media",
        "prompts_new",
        ["prompt_id"],
        ["_id"],
        onupdate="CASCADE",
    )
    op.drop_column("prompt_media", "file")
    # ### end Alembic commands ###
